apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-tests-go-jhhjclmk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/e2e-tests-go-jhhjclmk:9089cacaa0af4c9504b034dc3905cc4bb7e6576e
        name: container-image  
